export interface BasePhrase {
  text: string;
  snarkyRemark: string;
  difficulty: 1 | 2 | 3 | 4 | 5;
  category?: string;
}

export const basePhrases: BasePhrase[] = [
  // Difficulty 1: Easy - Basic short phrases (3-6 words)
  { text: "The cat is on the table.", snarkyRemark: "Basic feline geography.", difficulty: 1, category: "animals" },
  { text: "I like eating bread.", snarkyRemark: "The staple diet.", difficulty: 1, category: "food" },
  { text: "Where is the library?", snarkyRemark: "Keep studying.", difficulty: 1, category: "places" },
  { text: "The apple is red.", snarkyRemark: "Red and delicious.", difficulty: 1, category: "food" },
  { text: "Good morning, how are you?", snarkyRemark: "A friendly greeting.", difficulty: 1, category: "greetings" },
  { text: "My name is John.", snarkyRemark: "Identity matters.", difficulty: 1, category: "people" },
  { text: "I have a dog.", snarkyRemark: "Lucky you.", difficulty: 1, category: "animals" },
  { text: "The water is cold.", snarkyRemark: "Get used to it.", difficulty: 1, category: "nature" },
  { text: "Please help me.", snarkyRemark: "Polite request.", difficulty: 1, category: "sentences" },
  { text: "Thank you very much.", snarkyRemark: "Show gratitude.", difficulty: 1, category: "sentences" },
  { text: "I am a student.", snarkyRemark: "A lifelong learner.", difficulty: 1, category: "people" },
  { text: "The book is on the desk.", snarkyRemark: "Location matters.", difficulty: 1, category: "objects" },
  { text: "She is my sister.", snarkyRemark: "Family ties.", difficulty: 1, category: "people" },
  { text: "He drinks milk.", snarkyRemark: "Drink up.", difficulty: 1, category: "food" },
  { text: "We go to school.", snarkyRemark: "Going to school.", difficulty: 1, category: "places" },
  { text: "I eat an apple.", snarkyRemark: "Healthy choice.", difficulty: 1, category: "food" },
  { text: "The sky is blue.", snarkyRemark: "Blue sky.", difficulty: 1, category: "nature" },
  { text: "They are my friends.", snarkyRemark: "Friends matter.", difficulty: 1, category: "people" },
  { text: "I want to sleep.", snarkyRemark: "Rest needed.", difficulty: 1, category: "actions" },
  { text: "What time is it?", snarkyRemark: "Time check.", difficulty: 1, category: "questions" },
  { text: "The car is fast.", snarkyRemark: "Speed matters.", difficulty: 1, category: "transport" },
  { text: "I like music.", snarkyRemark: "Musical.", difficulty: 1, category: "art" },
  { text: "She wears a dress.", snarkyRemark: "Clothing choice.", difficulty: 1, category: "clothing" },
  { text: "He is a doctor.", snarkyRemark: "Medical profession.", difficulty: 1, category: "jobs" },
  { text: "We play soccer.", snarkyRemark: "Sporty.", difficulty: 1, category: "sports" },
  { text: "I live in a house.", snarkyRemark: "Home sweet home.", difficulty: 1, category: "places" },
  { text: "The dog is sleeping.", snarkyRemark: "Dreaming.", difficulty: 1, category: "animals" },
  { text: "She likes cats.", snarkyRemark: "Cat lover.", difficulty: 1, category: "animals" },
  { text: "He has a computer.", snarkyRemark: "Tech-savvy.", difficulty: 1, category: "technology" },
  { text: "I drink coffee.", snarkyRemark: "Caffeine boost.", difficulty: 1, category: "food" },
  { text: "The sun is bright.", snarkyRemark: "Bright day.", difficulty: 1, category: "nature" },
  { text: "I study English.", snarkyRemark: "Learning language.", difficulty: 1, category: "education" },
  { text: "The flower is beautiful.", snarkyRemark: "Nice flower.", difficulty: 1, category: "nature" },
  { text: "She works at a hospital.", snarkyRemark: "Healthcare worker.", difficulty: 1, category: "jobs" },
  { text: "The train arrives soon.", snarkyRemark: "Waiting.", difficulty: 1, category: "transport" },
  { text: "I write with a pen.", snarkyRemark: "Writing.", difficulty: 1, category: "actions" },
  { text: "The garden is beautiful.", snarkyRemark: "Nice garden.", difficulty: 1, category: "places" },
  { text: "I am hungry.", snarkyRemark: "Food time.", difficulty: 1, category: "feelings" },
  { text: "The store is closed.", snarkyRemark: "Shop closed.", difficulty: 1, category: "places" },
  { text: "I eat breakfast early.", snarkyRemark: "Morning meal.", difficulty: 1, category: "food" },
  { text: "Water is very cold.", snarkyRemark: "Cold water.", difficulty: 1, category: "nature" },
  { text: "The cat sleeps a lot.", snarkyRemark: "Lazy cat.", difficulty: 1, category: "animals" },
  { text: "Books are interesting.", snarkyRemark: "Reading is good.", difficulty: 1, category: "education" },
  { text: "Coffee tastes good.", snarkyRemark: "Good coffee.", difficulty: 1, category: "food" },
  { text: "Music makes happy.", snarkyRemark: "Happy music.", difficulty: 1, category: "art" },
  { text: "Rain falls from clouds.", snarkyRemark: "Rainy day.", difficulty: 1, category: "nature" },
  { text: "Time flies fast.", snarkyRemark: "Time passes.", difficulty: 1, category: "time" },
  { text: "The dog runs outside.", snarkyRemark: "Running dog.", difficulty: 1, category: "animals" },
  { text: "I walk to school.", snarkyRemark: "Walking.", difficulty: 1, category: "actions" },
  { text: "The sky is cloudy.", snarkyRemark: "Cloudy sky.", difficulty: 1, category: "nature" },
  { text: "I am very tired.", snarkyRemark: "Sleep time.", difficulty: 1, category: "feelings" },

  // Difficulty 2: Medium - More complex sentences (7-12 words)
  { text: "I would like to go to the park.", snarkyRemark: "A pleasant stroll.", difficulty: 2, category: "places" },
  { text: "The restaurant closes at ten o'clock.", snarkyRemark: "Hungry? Go now.", difficulty: 2, category: "food" },
  { text: "Can you help me find my way?", snarkyRemark: "Lost again.", difficulty: 2, category: "questions" },
  { text: "I have been studying for three hours.", snarkyRemark: "Dedicated student.", difficulty: 2, category: "education" },
  { text: "She wants to learn how to cook.", snarkyRemark: "Chef in the making.", difficulty: 2, category: "actions" },
  { text: "The movie starts in thirty minutes.", snarkyRemark: "Popcorn time.", difficulty: 2, category: "entertainment" },
  { text: "I think it is going to rain today.", snarkyRemark: "Weather forecast.", difficulty: 2, category: "nature" },
  { text: "He has been working here since 2020.", snarkyRemark: "Veteran employee.", difficulty: 2, category: "jobs" },
  { text: "Would you like some coffee or tea?", snarkyRemark: "Beverage choice.", difficulty: 2, category: "food" },
  { text: "The bus stop is near the supermarket.", snarkyRemark: "Public transport.", difficulty: 2, category: "transport" },
  { text: "I usually wake up at seven AM.", snarkyRemark: "Early bird.", difficulty: 2, category: "daily" },
  { text: "My favorite color is blue or green.", snarkyRemark: "Colorful preferences.", difficulty: 2, category: "preferences" },
  { text: "The children are playing in the garden.", snarkyRemark: "Happy kids.", difficulty: 2, category: "people" },
  { text: "I need to buy some new clothes.", snarkyRemark: "Shopping trip.", difficulty: 2, category: "shopping" },
  { text: "The doctor told me to rest more.", snarkyRemark: "Health advice.", difficulty: 2, category: "health" },
  { text: "We are going to visit my grandparents.", snarkyRemark: "Family visit.", difficulty: 2, category: "people" },
  { text: "It takes about two hours to drive.", snarkyRemark: "Road trip.", difficulty: 2, category: "transport" },
  { text: "I prefer reading books to watching TV.", snarkyRemark: "Bookworm.", difficulty: 2, category: "entertainment" },
  { text: "The weather is much better today.", snarkyRemark: "Sunny day.", difficulty: 2, category: "nature" },
  { text: "She studied medicine at the university.", snarkyRemark: "Future doctor.", difficulty: 2, category: "education" },
  { text: "I forgot to bring my umbrella.", snarkyRemark: "Wet day.", difficulty: 2, category: "weather" },
  { text: "The hotel room is very comfortable.", snarkyRemark: "Cozy stay.", difficulty: 2, category: "travel" },
  { text: "We should leave early tomorrow morning.", snarkyRemark: "Early start.", difficulty: 2, category: "time" },
  { text: "I have already finished my homework.", snarkyRemark: "Good student.", difficulty: 2, category: "education" },
  { text: "The train ticket costs twenty euros.", snarkyRemark: "Pricey ride.", difficulty: 2, category: "money" },
  { text: "She speaks three languages fluently.", snarkyRemark: "Polyglot.", difficulty: 2, category: "languages" },
  { text: "I am meeting my friends tonight.", snarkyRemark: "Social life.", difficulty: 2, category: "people" },
  { text: "The museum opens at nine in the morning.", snarkyRemark: "Culture time.", difficulty: 2, category: "places" },
  { text: "I need to call my mother immediately.", snarkyRemark: "Family call.", difficulty: 2, category: "communication" },
  { text: "The shoes are too small for me.", snarkyRemark: "Size matters.", difficulty: 2, category: "clothing" },
  { text: "We enjoyed the concert last weekend.", snarkyRemark: "Great music.", difficulty: 2, category: "entertainment" },
  { text: "I usually have lunch at noon.", snarkyRemark: "Lunch time.", difficulty: 2, category: "food" },
  { text: "The bridge was built many years ago.", snarkyRemark: "History.", difficulty: 2, category: "places" },
  { text: "Can I ask you a personal question?", snarkyRemark: "Curious.", difficulty: 2, category: "questions" },
  { text: "I will meet you at the coffee shop.", snarkyRemark: "Caffeine date.", difficulty: 2, category: "places" },
  { text: "The food tasted delicious and fresh.", snarkyRemark: "Yummy.", difficulty: 2, category: "food" },
  { text: "She arrived just a few minutes ago.", snarkyRemark: "Fashionably late.", difficulty: 2, category: "time" },
  { text: "I want to travel around the world.", snarkyRemark: "Wanderlust.", difficulty: 2, category: "travel" },
  { text: "The book was more interesting than expected.", snarkyRemark: "Good read.", difficulty: 2, category: "entertainment" },

  // Difficulty 3: Hard - Complex sentences with idioms (12-18 words)
  { text: "Better late than never, they always say.", snarkyRemark: "Proverbial wisdom.", difficulty: 3, category: "idioms" },
  { text: "The proof of the pudding is in the eating, as they say.", snarkyRemark: "You must try it.", difficulty: 3, category: "idioms" },
  { text: "I cannot believe he actually said that in front of everyone.", snarkyRemark: "Awkward moment.", difficulty: 3, category: "people" },
  { text: "If you do not ask, you will never know the answer to your question.", snarkyRemark: "Curiosity rewarded.", difficulty: 3, category: "advice" },
  { text: "She decided to take the risk and start her own business despite the challenges.", snarkyRemark: "Entrepreneurial spirit.", difficulty: 3, category: "jobs" },
  { text: "The more you practice, the better you will become at speaking any language.", snarkyRemark: "Practice makes perfect.", difficulty: 3, category: "education" },
  { text: "I would have called you earlier if I had known you were waiting for me.", snarkyRemark: "Apology accepted.", difficulty: 3, category: "communication" },
  { text: "It has been raining continuously for the past week, which is quite unusual for this season.", snarkyRemark: "Weather woes.", difficulty: 3, category: "nature" },
  { text: "Even though the restaurant was fully booked, they managed to find us a table.", snarkyRemark: "Lucky break.", difficulty: 3, category: "food" },
  { text: "The scientist explained the complex theory in simple terms that even a child could understand.", snarkyRemark: "Teaching skill.", difficulty: 3, category: "education" },
  { text: "No matter how hard you try, sometimes things just do not work out the way you planned.", snarkyRemark: "Life lessons.", difficulty: 3, category: "philosophy" },
  { text: "I have been looking forward to this moment since the first day we met each other.", snarkyRemark: "Anticipation.", difficulty: 3, category: "feelings" },
  { text: "The old man who lived in the small cottage by the river was known for his wisdom.", snarkyRemark: "Village sage.", difficulty: 3, category: "people" },
  { text: "Because of the heavy traffic on the highway, we arrived at the airport almost too late.", snarkyRemark: "Traffic blues.", difficulty: 3, category: "transport" },
  { text: "If I were you, I would think twice before making such an important decision without advice.", snarkyRemark: "Think before you act.", difficulty: 3, category: "advice" },
  { text: "The company announced that they will be expanding their operations to several new countries.", snarkyRemark: "Business growth.", difficulty: 3, category: "jobs" },
  { text: "Although she was nervous about the interview, she managed to stay calm and confident throughout.", snarkyRemark: "Interview ace.", difficulty: 3, category: "jobs" },
  { text: "The unexpected phone call from an old friend completely changed her plans for the weekend.", snarkyRemark: "Surprise visit.", difficulty: 3, category: "communication" },
  { text: "I remember when we used to play together in the park every afternoon after school.", snarkyRemark: "Nostalgia.", difficulty: 3, category: "memories" },
  { text: "The chef demonstrated how to prepare the traditional dish while explaining the history behind it.", snarkyRemark: "Culinary art.", difficulty: 3, category: "food" },
  { text: "Despite the many difficulties they faced, the team continued working together until they succeeded.", snarkyRemark: "Team spirit.", difficulty: 3, category: "work" },
  { text: "The book you recommended turned out to be one of the most fascinating reads of my life.", snarkyRemark: "Great recommendation.", difficulty: 3, category: "entertainment" },
  { text: "Unless you practice speaking every day, it will be very difficult to become fluent in any language.", snarkyRemark: "Daily practice.", difficulty: 3, category: "education" },
  { text: "The teacher explained that understanding grammar is essential for communicating effectively in any language.", snarkyRemark: "Grammar matters.", difficulty: 3, category: "education" },
  { text: "After finishing the marathon, the athlete was so exhausted that he could barely walk home.", snarkyRemark: "Runner's exhaustion.", difficulty: 3, category: "sports" },
  { text: "Because of the global pandemic, many businesses had to adapt to new ways of working remotely.", snarkyRemark: "Modern challenges.", difficulty: 3, category: "work" },
  { text: "The lawyer argued persuasively in court, convincing the jury of his client's innocence.", snarkyRemark: "Legal victory.", difficulty: 3, category: "law" },
  { text: "I wish I had studied harder when I was younger instead of wasting so much time playing games.", snarkyRemark: "Regretful thoughts.", difficulty: 3, category: "reflections" },
  { text: "The travel agent helped us plan an amazing vacation that we will remember for the rest of our lives.", snarkyRemark: "Dream vacation.", difficulty: 3, category: "travel" },

  // Difficulty 4: Expert - Very long sentences, proverbs, complex grammar (18-25 words)
  { text: "A stitch in time saves nine, as the old saying goes, so it is better to fix problems early rather than wait until they become worse.", snarkyRemark: "Prevention is better than cure.", difficulty: 4, category: "idioms" },
  { text: "The interdisciplinary team of scientists from various universities collaborated for five years to develop this groundbreaking治疗方法 that could revolutionize medicine.", snarkyRemark: "Scientific breakthrough.", difficulty: 4, category: "science" },
  { text: "In spite of all the obstacles and setbacks they encountered along the way, their determination and perseverance finally paid off with spectacular results.", snarkyRemark: "Perseverance wins.", difficulty: 4, category: "motivation" },
  { text: "Had I known about the traffic jam earlier in the morning, I would have left for the airport much earlier than I actually did.", snarkyRemark: "Hindsight.", difficulty: 4, category: "time" },
  { text: "The comprehensive analysis of the historical documents revealed that the ancient civilization was far more advanced than previously believed by modern scholars.", snarkyRemark: "Historical discovery.", difficulty: 4, category: "history" },
  { text: "Not only did she win the international competition, but she also set a new world record that had stood for more than a decade.", snarkyRemark: "World champion.", difficulty: 4, category: "sports" },
  { text: "The environmental scientists warned that unless immediate and drastic measures are taken to reduce carbon emissions, the consequences for our planet will be catastrophic.", snarkyRemark: "Climate warning.", difficulty: 4, category: "environment" },
  { text: "It is remarkable how a simple act of kindness from a stranger can completely brighten someone's entire day and restore their faith in humanity.", snarkyRemark: "Kindness matters.", difficulty: 4, category: "philosophy" },
  { text: "The psychological study demonstrated that people who practice gratitude daily tend to experience significantly higher levels of happiness and well-being.", snarkyRemark: "Science of happiness.", difficulty: 4, category: "psychology" },
  { text: "Despite having studied the language for over ten years and living in the country for five, she still struggles with some of the more nuanced colloquial expressions.", snarkyRemark: "Language learning.", difficulty: 4, category: "education" },
  { text: "The economic report predicted that unless the government implements new policies to stimulate growth, the country could face a prolonged period of stagnation.", snarkyRemark: "Economic forecast.", difficulty: 4, category: "economics" },
  { text: "The architecture of this ancient temple is so sophisticated that modern engineers are still trying to understand how our ancestors built it without modern technology.", snarkyRemark: "Engineering marvel.", difficulty: 4, category: "history" },
  { text: "It is often said that the journey is more important than the destination, but in this case the destination proved to be equally rewarding and fulfilling.", snarkyRemark: "Life journey.", difficulty: 4, category: "philosophy" },
  { text: "The autobiography traced the author's remarkable life from humble beginnings as a farmer's son to becoming one of the most influential leaders of his generation.", snarkyRemark: "Inspiring story.", difficulty: 4, category: "biography" },
  { text: "Although the technology company had invested billions of dollars in research and development, they ultimately decided to abandon the project due to unforeseen technical challenges.", snarkyRemark: "Tech setbacks.", difficulty: 4, category: "technology" },
  { text: "The philosophical debate about free will versus determinism has puzzled thinkers for millennia, and there is still no definitive answer in sight.", snarkyRemark: "Ancient debate.", difficulty: 4, category: "philosophy" },
  { text: "The combination of traditional farming methods with cutting-edge agricultural technology has resulted in unprecedented increases in crop yield and sustainability.", snarkyRemark: "Agricultural innovation.", difficulty: 4, category: "science" },
  { text: "If it had not been for the courageous intervention of the bystander who risked his own safety to help others, the accident could have resulted in many more casualties.", snarkyRemark: "Heroic act.", difficulty: 4, category: "people" },
  { text: "The documentary explored how the small coastal town had transformed over the past century from a sleepy fishing village into a bustling international tourist destination.", snarkyRemark: "Transformation.", difficulty: 4, category: "society" },
  { text: "The medical breakthrough discovered by the research team offers hope to millions of patients suffering from this previously incurable disease.", snarkyRemark: "Medical miracle.", difficulty: 4, category: "health" },

  // Difficulty 5: Master - Literary, archaic, highly nuanced (25+ words, complex structures)
  { text: "Notwithstanding the myriad of challenges that bespoke upon our intrepid explorers as they traversed the uncharted territories of the New World, their unwavering resolve and camaraderie ensured that their expedition would be immortalized in the annals of history for generations to come.", snarkyRemark: "Epic expedition.", difficulty: 5, category: "literary" },
  { text: "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife, however, nowadays such antiquated notions have been supplanted by more egalitarian perspectives on matrimony and personal fulfillment.", snarkyRemark: "Austen's irony.", difficulty: 5, category: "literature" },
  { text: "The unexamined life is not worth living, proclaimed Socrates, and yet in our modern era of ceaseless distraction and ephemeral pleasures, the art of contemplation has become a rarity rather than the norm among the populace.", snarkyRemark: "Philosophical musing.", difficulty: 5, category: "philosophy" },
  { text: "Insofar as the corpus of linguistic scholarship has demonstrated, the acquisition of fluency in any natural language demands not merely rote memorization of vocabulary but also an profound immersion in the cultural contexts from which said language emanates.", snarkyRemark: "Linguistic academia.", difficulty: 5, category: "education" },
  { text: "The labyrinthine complexities of human emotion, with their inextricable interweaving of joy and sorrow, hope and despair, love and loss, continue to confound even the most eminent psychologists and philosophers throughout the ages.", snarkyRemark: "Emotional depths.", difficulty: 5, category: "psychology" },
  { text: "Notwithstanding the fact that contemporary society prides itself upon its technological advancements and computational prowess, the fundamental questions regarding the nature of consciousness, the existence of the soul, and the meaning of existence remain as elusive as ever.", snarkyRemark: "Existential queries.", difficulty: 5, category: "philosophy" },
  { text: "The historiographical debate surrounding the fall of the Roman Empire has raged for centuries, with some scholars attributing it to external invasions while others point to internal decay and economic decline as the primary causative factors.", snarkyRemark: "Historical analysis.", difficulty: 5, category: "history" },
  { text: "As the venerable professor expounded upon the intricacies of quantum mechanics and the observer effect, the young students sat in rapt attention, their minds grappling with concepts that seemed to transcend the boundaries of conventional physical reality.", snarkyRemark: "Quantum wonder.", difficulty: 5, category: "science" },
  { text: "The epic poem, written in the Homeric tradition, chronicled the trials and tribulations of the hero as he journeyed across the known world, facing monsters, temptresses, and gods alike, all in pursuit of a glory that would echo through eternity.", snarkyRemark: "Epic narrative.", difficulty: 5, category: "literature" },
  { text: "In the final analysis, it became abundantly clear that the confluence of geopolitical forces, economic pressures, and cultural misunderstandings had created a perfect storm that would reshape the international order for decades to come.", snarkyRemark: "Geopolitical analysis.", difficulty: 5, category: "politics" },
  { text: "The literary critic argued persuasively that the author's use of stream-of-consciousness narrative technique was not merely an exercise in stylistic experimentation but rather a profound exploration of the fragmented nature of human perception and memory.", snarkyRemark: "Literary analysis.", difficulty: 5, category: "literature" },
  { text: "The Renaissance masters, with their unparalleled mastery of perspective, chiaroscuro, and anatomical accuracy, created works of such breathtaking beauty and technical perfection that they continue to inspire artists and enthusiasts more than five centuries later.", snarkyRemark: "Artistic mastery.", difficulty: 5, category: "art" },
  { text: "As the storm of public opinion raged around the embattled politician, he remained stoic in his convictions, knowing that history would ultimately vindicate those who had the courage to speak truth to power, regardless of the personal consequences.", snarkyRemark: "Political courage.", difficulty: 5, category: "politics" },
  { text: "The sociological study revealed the stark disparities in educational outcomes between affluent and disadvantaged communities, demonstrating that systemic inequalities continue to perpetuate cycles of poverty across generations despite well-intentioned policy interventions.", snarkyRemark: "Social inquiry.", difficulty: 5, category: "society" },
  { text: "The ancient philosophical treatise, written in a now-extinct language and deciphered only recently through the painstaking work of generations of linguists, offered unprecedented insights into the metaphysical beliefs of a civilization long thought lost to history.", snarkyRemark: "Lost wisdom.", difficulty: 5, category: "philosophy" },
];

export const languages = [
  { name: 'Spanish', code: 'es', color: '#FF6B6B', hover: '#FF8787' },
  { name: 'Greek', code: 'el', color: '#4ECDC4', hover: '#6EDCD5' },
  { name: 'English', code: 'en', color: '#95E1D3', hover: '#A8E6CF' },
  { name: 'German', code: 'de', color: '#F38181', hover: '#F5A3A3' },
  { name: 'Chinese', code: 'zh-CN', color: '#AA96DA', hover: '#C2B0E8' }
];

export function shuffleArray<T>(array: T[]): T[] {
  const newArray = [...array];
  for (let i = newArray.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [newArray[i], newArray[j]] = [newArray[j], newArray[i]];
  }
  return newArray;
}
